"""事件契约（runtime 输出）：RunEvent 生命周期 + 展示增量事件（react-runtime-v2-architecture §17）。

旧 AgentEvent 会话事件模型已整体下架（v2 统一 RunEvent 输出）；HTTP/SSE 只负责
经 run_stream.map_run_event 映射，不感知 LangGraph 内部节点（§21）。
"""

from app.runtime.events.emitter import QueueEmitter
from app.runtime.events.run_events import (
    ActionProposed,
    ActionRejected,
    ContractChecked,
    Heartbeat,
    LLMCallStarted,
    LLMUsageUpdated,
    PhaseCompleted,
    PhaseStarted,
    ProgressStalled,
    ProgressUpdated,
    RunCancelled,
    RunCompleted,
    RunDegraded,
    RunEvent,
    RunEventUnion,
    RunFailed,
    RunFinalizing,
    RunInputRequested,
    RunStarted,
    TextDelta,
    ThinkingDelta,
    ThinkingEnded,
    ThinkingStarted,
    ToolCallCompleted,
    ToolCallStarted,
    run_event_adapter,
)

__all__ = [
    "ActionProposed",
    "ActionRejected",
    "ContractChecked",
    "Heartbeat",
    "LLMCallStarted",
    "LLMUsageUpdated",
    "PhaseCompleted",
    "PhaseStarted",
    "ProgressStalled",
    "ProgressUpdated",
    "QueueEmitter",
    "RunCancelled",
    "RunCompleted",
    "RunDegraded",
    "RunEvent",
    "RunEventUnion",
    "RunFailed",
    "RunFinalizing",
    "RunInputRequested",
    "RunStarted",
    "TextDelta",
    "ThinkingDelta",
    "ThinkingEnded",
    "ThinkingStarted",
    "ToolCallCompleted",
    "ToolCallStarted",
    "run_event_adapter",
]
