[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

addopts = -s
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s │ %(levelname)-7s │ P:%(process)-5d T:%(thread)-5d │ %(filename)s:%(lineno)-3d │ %(funcName)s ── %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S