"""initial schema: upload_files + dedup_clues

Revision ID: 0a7be955b1c4
Revises: 
Create Date: 2026-08-21 14:15:42.421074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a7be955b1c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_clues',
    sa.Column('clue_id', sa.String(length=128), nullable=False),
    sa.Column('product_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_industry', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('remaining_pool', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('clue_id', name=op.f('pk_dedup_clues'))
    )
    op.create_table('upload_files',
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_upload_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_upload_files_storage_key'))
    )
    op.create_index(op.f('ix_upload_files_agent_id'), 'upload_files', ['agent_id'], unique=False)
    op.create_index(op.f('ix_upload_files_session_id'), 'upload_files', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_files_session_id'), table_name='upload_files')
    op.drop_index(op.f('ix_upload_files_agent_id'), table_name='upload_files')
    op.drop_table('upload_files')
    op.drop_table('dedup_clues')
    # ### end Alembic commands ###
