"""conversations messages upload_files usage

Revision ID: ea8172ad144a
Revises: 0a7be955b1c4
Create Date: 2026-08-26 11:29:54.534509

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8172ad144a'
down_revision: str | None = '0a7be955b1c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dialogue_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('thinking', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_write_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_agent_id'), 'messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # upload_files 重构：filename → name 重命名保留数据；新 NOT NULL 列加
    # server_default 兼容既有行（storage_type=local / created_by_role=agent /
    # used=false / extension=''）
    op.add_column('upload_files', sa.Column('storage_type', sa.String(length=16), server_default='local', nullable=False))
    op.add_column('upload_files', sa.Column('extension', sa.String(length=64), server_default='', nullable=False))
    op.add_column('upload_files', sa.Column('hash', sa.String(length=128), nullable=True))
    op.add_column('upload_files', sa.Column('created_by_role', sa.String(length=32), server_default='agent', nullable=False))
    op.add_column('upload_files', sa.Column('used', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('upload_files', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('upload_files', 'filename', new_column_name='name',
                    existing_type=sa.String(length=255), existing_nullable=False)
    op.drop_index(op.f('ix_upload_files_agent_id'), table_name='upload_files')
    op.drop_index(op.f('ix_upload_files_session_id'), table_name='upload_files')
    op.drop_column('upload_files', 'session_id')
    op.drop_column('upload_files', 'agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_files', sa.Column('agent_id', sa.String(length=64), server_default='', nullable=False))
    op.add_column('upload_files', sa.Column('session_id', sa.String(length=32), server_default='', nullable=False))
    op.alter_column('upload_files', 'name', new_column_name='filename',
                    existing_type=sa.String(length=255), existing_nullable=False)
    op.create_index(op.f('ix_upload_files_session_id'), 'upload_files', ['session_id'], unique=False)
    op.create_index(op.f('ix_upload_files_agent_id'), 'upload_files', ['agent_id'], unique=False)
    op.drop_column('upload_files', 'used_at')
    op.drop_column('upload_files', 'used')
    op.drop_column('upload_files', 'created_by_role')
    op.drop_column('upload_files', 'hash')
    op.drop_column('upload_files', 'extension')
    op.drop_column('upload_files', 'storage_type')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_agent_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
